spring:
  datasource:
    druid:
      master:
        url: ${RUOYI_MASTER_DATASOURCE_URL:jdbc:mysql://172.16.46.202:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
        username: ${RUOYI_MASTER_DATASOURCE_USERNAME:ry-vue}
        password: ${RUOYI_MASTER_DATASOURCE_PASSWORD:}
